<?php

namespace Hn\UserBundle\Repository;

/**
 * BackendUsersRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BackendUsersRepository extends \Doctrine\ORM\EntityRepository
{
}
