hn_sw_wechat_index:
    path:     /
    defaults: { _controller: HnSwBundle:WeChat/Index:index }

hn_sw_wechat_check:
    path:     /check
    defaults: { _controller: HnSwBundle:WeChat/Index:check }

hn_sw_wechat_menu:
    path:     /menu
    defaults: { _controller: HnSwBundle:WeChat/Index:createWxMenu }


hn_sw_wechat_pay:
    path:     /pay
    defaults: { _controller: HnSwBundle:WeChat/Index:pay }

hn_sw_wechat_record:
    path:     /record
    defaults: { _controller: HnSwBundle:WeChat/Index:record }

hn_sw_wechat_ajax_record:
    path:     /ajax/record
    defaults: { _controller: HnSwBundle:WeChat/Index:ajaxUploadRecord }
