backend_goods_type_index:
    path:     /index
    defaults: { _controller: HnSwBundle:Backend/GoodsType:index }

backend_goods_type_new:
    path:     /new
    defaults: { _controller: HnSwBundle:Backend/GoodsType:new }

backend_goods_type_property:
    path:     /property/{tid}/index
    defaults: { _controller: HnSwBundle:Backend/GoodsType:property }

backend_goods_type_property_new:
    path:     /property/{tid}/new
    defaults: { _controller: HnSwBundle:Backend/GoodsType:newProperty }