backend_goods_category_index:
    path:     /index
    defaults: { _controller: HnSwBundle:Backend/GoodsCategory:index }

backend_goods_category_new:
    path:     /new
    defaults: { _controller: HnSwBundle:Backend/GoodsCategory:new }

backend_goods_category_new_son_cate:
    path:     /new/{pid}/son/cate
    defaults: { _controller: HnSwBundle:Backend/GoodsCategory:newSonCate }