<?php

namespace Hn\SwBundle\Repository;

/**
 * GoodsAttrValueRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GoodsAttrValueRepository extends \Doctrine\ORM\EntityRepository
{
}
