<?php

namespace Hn\SwBundle\Repository;
use Hn\SwBundle\Entity\GoodsTypeAttr;

/**
 * GoodsTypeAttrRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GoodsTypeAttrRepository extends \Doctrine\ORM\EntityRepository
{
    public function getTidAttr($tid)
    {
        $query = $this
            ->_em
            ->createQueryBuilder('g')
            ->from(GoodsTypeAttr::class,'g')
            ->select('g')
            ->where('g.tid = '.$tid)
            ->getQuery()
        ;

        $data = $query->getArrayResult();

        return $data;
    }
}
