<?php

namespace Hn\SwBundle\Repository;
use Hn\SwBundle\Entity\GoodsAttrValue;

/**
 * GoodsAttrValueRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GoodsAttrValueRepository extends \Doctrine\ORM\EntityRepository
{
    public function getTaidAttrValue($taid)
    {
        $query = $this
            ->_em
            ->createQueryBuilder('g')
            ->from(GoodsAttrValue::class,'g')
            ->select('g.value')
            ->where('g.taid = '.$taid)
            ->getQuery()
        ;

        $data = $query->getArrayResult();

        return $data;
    }
}
