<?php

namespace Hn\SwBundle\Repository;

/**
 * GoodsTypeAttrRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GoodsTypeAttrRepository extends \Doctrine\ORM\EntityRepository
{
}
