<?php

namespace Hn\SwBundle\Repository;

/**
 * GoodsTypeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GoodsTypeRepository extends \Doctrine\ORM\EntityRepository
{
}
