hn_sw:
    resource: "@HnSwBundle/Resources/config/routing.yml"
    prefix:   /

hn_sw_homepage:
    path:     /
    defaults: { _controller: HnSwBundle:Default:index }


_liip_imagine:
    resource: "@LiipImagineBundle/Resources/config/routing.xml"


hn_sw_pro:
    path:     /procreate
    defaults: { _controller: HnSwBundle:Default:create }

hn_sw_proshow:
    path:     /proshow
    defaults: { _controller: HnSwBundle:Default:show }