# To get started with security, check out the documentation:
# http://symfony.com/doc/current/security.html
security:
    encoders:
        Hn\UserBundle\Entity\Users:
            algorithm: bcrypt

        Hn\UserBundle\Entity\BackendUsers:
            algorithm: bcrypt

    providers:
        chain_provider:
            chain:
                providers: [user_db, backend_user_db]

        user_db:
            entity: { class: Hn\UserBundle\Entity\Users, property: username }

        backend_user_db:
            entity: { class: Hn\UserBundle\Entity\BackendUsers, property: username }

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            anonymous: ~
            # activate different ways to authenticate

            # http://symfony.com/doc/current/security.html#a-configuring-how-your-users-will-authenticate
            #http_basic: ~

            # http://symfony.com/doc/current/cookbook/security/form_login_setup.html
            #form_login: ~
    acl:
        connection: default