# To get started with security, check out the documentation:
# http://symfony.com/doc/current/security.html
security:
    encoders:
        Hn\UserBundle\Entity\User:
            algorithm: bcrypt

        Hn\UserBundle\Entity\BackendUser:
            algorithm: bcrypt

    providers:
        chain_provider:
            chain:
                providers: [user_db, backend_user_db]

        user_db:
            entity: { class: Hn\UserBundle\Entity\User, property: username }

        backend_user_db:
            entity: { class: Hn\UserBundle\Entity\BackendUser, property: username }

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            anonymous: ~
            # activate different ways to authenticate

            # http://symfony.com/doc/current/security.html#a-configuring-how-your-users-will-authenticate
            #http_basic: ~

            # http://symfony.com/doc/current/cookbook/security/form_login_setup.html
            #form_login: ~
            form_login:
                provider: user_db
                login_path: /user/login
                check_path: /user/login
                default_target_path: /

            logout:
                path:   /user/logout
                target: /

            remember_me:
                secret:   '%secret%'
                lifetime: 2592000
                path:     /
    acl:
        connection: default