hn_sw_backend_all:
    resource: "@HnSwBundle/Resources/config/routing/backend/back_all.yml"
    prefix:   /admin

hn_sw_wechat_all:
    resource: "@HnSwBundle/Resources/config/routing/wechat/wechat_all.yml"
    prefix:   /wx






hn_sw_test_alipay:
    path:     /alipay
    defaults: { _controller: HnSwBundle:Test:aliPay }


