services:
    tree_data:
        class: Hn\SwBundle\Services\Tool\DataTree

    ali_pay:
        class: Hn\SwBundle\Services\AliPay\HnPay

    sw_wechat:
        class: Hn\SwBundle\Services\WeChat\SwWeChat
        arguments: ['@service_container']